### PR TITLE
Add GraphQL::Execution::Errors module

### PR DESCRIPTION
**Pull request by AleksandrSeleznev**
### Summary

@ArthurZaharov suggested to implement these `GraphQL::Execution::Errors` module in order to be able to handle errors.

### How it works

We can handle errors with `rescue_from` method. For example, for `ActiveRecord::RecordNotFound`:
```ruby
rescue_from(ActiveRecord::RecordNotFound) do |_err, _obj, _args, _ctx, field|
    raise GraphQL::ExecutionError.new("#{field.type.unwrap.graphql_name} not found",
                                      extensions: { message: "Not Found", status: 404, code: :not_found })
  end
```
### Test plan

N/A

### Review notes

While reviewing pull-request (especially when it's your pull-request),
please make sure that:

- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduced DB fields have indexes and constraints
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes

### Deploy notes

N/A

### References
N/A

### CODE REVIEW

**Comment by EvgeniyEsaulkov** [comment]
Can you please add a test for some graphql query or mutation that illustrates how it work?

**Comment by AleksandrSeleznev** [comment]
> Can you please add a test for some graphql query or mutation that illustrates how it work?

@EvgeniyEsaulkov is it necessary to implement separated spec for this? 
I haven't found any query or mutation with `find` method for some `Model`, only `find_by`.

**Comment by EvgeniyEsaulkov** [comment]
> I haven't found any query or mutation with find method for some Model, only find_by

That's why I asked :-)
What are the benefits to add code that probably will used never? And in case we will use `.find` in some query or mutation in the future, would it better to [specify error explicitely](https://github.com/fs/rails-base-graphql-api/issues/128#issuecomment-812980887) in application schema?

**Comment by EvgeniyEsaulkov** [comment]
@AleksandrSeleznev I discussed addding of errors to Application Schema with FE developers - they are not happy with that. So I think we can use your solution for now - every project we started on the base of `rails-base-graphql-api` uses `.find` method.

**Review by EvgeniyEsaulkov — APPROVED** [review]

**Review by ArthurZaharov — APPROVED** [review]

**Pull request merged**
