### PR TITLE
Prettify Graphql logs

### LINKED ISSUE #102: Investigate how to prettify graphql logs
Use GraphQL::Language::Printer for this.

### PR DESCRIPTION
**Pull request by AzatZaynutdinov**
### Summary

Prettify Graphql logs

### How it works

Before
Screenshot_20200720_102359

After

image

### Test plan

List of steps to manually test introduced functionality:

* Open GraphiQL App
* Make request using schema:
```
  query {
    me: {
      id
      name
    }
  }
```
* ...

### Review notes

While reviewing pull-request (especially when it's your pull-request),
please make sure that:

- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduced DB fields have indexes and constraints
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes

### Deploy notes

Notes regarding deployment the contained body of work.
These should note any db migrations, ENV variables, services, scripts, etc.

### References
* Resolves #102 Issue

### CODE REVIEW

**Comment by ArthurZaharov** [comment]
@AzatZaynutdinov Have you tied this gem - https://github.com/jetruby/graphql-rails_logger?

**Comment by AzatZaynutdinov** [comment]
@ArthurZaharov I looked at this gem. It has some functionality, but it's +1 dependency

**Comment by ArthurZaharov** [comment]
@AzatZaynutdinov Seems like it is a very small dependency. And if it provides all features that we need or solve our issue we should use it.

**Review by EvgeniyEsaulkov — APPROVED** [review]

**Comment by EvgeniyEsaulkov** [comment]
@ArthurZaharov can we merge this PR?

**Comment by ArthurZaharov** [comment]
@EvgeniyEsaulkov we need to review it before merge

**Comment by ArthurZaharov** [comment]
@EvgeniyEsaulkov I check this PR. It works as I think. Previously issue was with filtering sensitive data in the logs. If we will use query variables it works perfect. Without query variables it does not filter fields (password for example)
Screenshot 2021-02-04 at 01 21 23
Screenshot 2021-02-04 at 01 21 53

**Review by ArthurZaharov — APPROVED** [review]

**Pull request merged**
